* bib todo
** AltLink: Replace archive.today links with archive.org links
*** Job Request
- https://www.quora.com/Is-there-a-good-website-to-hire-cheap-freelancers-for-basic-data-entry
- https://www.freelancer.com
- I am looking for a freelancer to help me fix citation entries in my
  bibliography. There is no citation style. The parts are "tagged."  I
  am flexible with the time 1 to 4 months.  There are 70 to 80
  citation links that need to be fixed. I think an average of
  5min/entry would be needed.  See attached file for directions and
  examples.

*** For Media: link, fixup the AltLink tags
  - The archive.vn links in AltLink are mostly broken. Replace them with
    web.archive.org page links.
  1. Go to https://archive.org/web/ (the Wayback Machine at Internet
    Archive)
  2. Enter the orginal Link url
  3. Find a copy at or just after the cited Date
    - if there is more than one copy for the Date, use the one with
      the latest time.
    - Or use the "Wayback Machine" Chrome extension (see below)
  4. Put the archive.org url in AltLink
  5. Create a tinyurl for the link
  6. Put the tinyurl in AltLink at the beginning
  7. If the date is "very" different, remove the archive.vn link,
    otherwise put it at the end
  8. Update the Date to match the archive.org date.

**** Using Chrome extension
  1. Add "Wayback Machine" Chrome extension
    - Wayback Machine Chrome Extension
    - https://chrome.google.com/webstore/detail/wayback-machine/fpnmgdkabkmnadcjpehmlllkndpkmiak?hl=en-US
    - https://tinyurl.com/app
  2. Enter the orginal Link url
  3. Click on the chrome extension, then click on "Save Page Now" or "Newest"
  4. Continue with steps 4 to 8.

**** Exceptions
  - If the archive.org date is close to the date "in the article,"
    then don't change the Date:
  - If the date in the article is very different from the date in the AltLink reference,
    then put the AltLink date in DateSeen:
  - If Date is missing, follow the archive.vn AltLink to get the date.
    - If the archive.vn does not work, then find the newest date in
      archive.org.  (the Wayback Machine Chrome extention can be
      used.)
  - If a Link url is not found in archive.org, then the Wayback Machine Chrome
    extention can be used to archive the page.
  - If the Link url is not found at all, then add or update the Annote: line with a
    short problem description. For example: Link not found.
  - If the archive.vn Date is very different, delete the archive.vn link
  - Problems or exceptions can be noted in the Annote: line.

**** Note:
  - All the text after a "tag" is all on one line. There are no line breaks.
  - AltLink urls are space separated.

*** For Type: book, Fixup Date, Publisher, Link
  1.  Lookup the book in amazon.com. If there is an amazon.com Link, use that
  2. Select Kindle, if Media is Ebook. Or select Paperback, or Hardback
  3. Add or update Link, remove "ref=" and all after that from the URL
  4. Sroll down to find the Publisher, add that tag, removing any city and date parts.
  5. Add or update the Date. Include the full date if you see that. YYYY-MM-DD
  6. If there are multiple authors, put the first author after the Author
    tag. Put the other authors after an Authors tag. Last, First,
    separated with a ';'
  7. If you see ISBN, add that tag
  8. If no ISBN, and there is an ASIN, then add ASIN
  9. Shorten amazon links, if they still work. For example:
    - Old Link: https://www.amazon.com/Lost-Cause-Cory-Doctorow-ebook/dp/B0BQGGP2XT/ref=sr_1_1?crid=33GC3LJO9WQJ&keywords=lost+cause&qid=1702359164&s=digital-text&sprefix=lost+cause%2Cdigital-text%2C245&sr=1-1
    - Short Link: https://www.amazon.com/dp/B0BQGGP2XT

*** Example
**** Before

    Id: demarco-03
    Type: book
    Media: Paperback
    Title: Waltzing With Bears: Managing Risk on Software Projects
    Author: DeMarco, Tom
    Date: 2003
    Publisher: Dorset House
    Tags: biblio, engineering
    ISBN: 0932633609
    ASIN: 188256

Id: doctorow-16
Type: book
Media: Ebook
Title: The Lost Cause
Author: Doctorow, Cory
Date: 2023-11-14
Publisher: Tor Books
Link: https://www.amazon.com/Lost-Cause-Cory-Doctorow-ebook/dp/B0BQGGP2XT
AltLink: https://craphound.com/category/lostcause/

Id: little-01
Type: article
Media: link
Title: The Lure of Obedience
Author: Little, Mat
Date: 2012-07-13
Publisher: New Compass, Grenmarsvegen 12, 3912 Porsgrunn, Norway
Link: http://new-compass.net/articles/lure-obedience
AltLink: https://archive.vn/GrqpI
Annote: See notes.

Id: macy-01
Type: book
Media: Ebook
Title: Coming back to life : the updated guide to the work that reconnects
Author: Macy, Joanna
Date: 2014
Publisher: Gabriola Island, BC, Canada : New Society Publishers, 2014.
Tags: biblio, important
ISBN: 1550925806
ASIN: 1401243

Id: nfnc-01
Type: site
Media: org
Title: Network For a New Culture :: Home
Tags: culture, link, biblio, link
Link: http://www.nfnc.org/

Id: wikipedia-48
Type: article
Media: link
Title: Dunbar's number
Date: 2023-06-20
Link: https://en.wikipedia.org/wiki/Dunbar%27s_number
AltLink: https://archive.vn/b1ora

**** After

Id: demarco-03
Type: book
Media: Paperback
Title: Waltzing With Bears: Managing Risk on Software Projects
Author: DeMarco, Tom
Authors: Lister, Timothy
Date: 2003-01-01
Publisher: Dorset House
Tags: biblio, engineering
ISBN: 0932633609
Link: https://www.amazon.com/gp/product/0932633609/
Annote: added authors, extended date, added link

Id: doctorow-16
Type: book
Media: Ebook
Title: The Lost Cause
Author: Doctorow, Cory
Date: 2023-11-14
Publisher: Tor Books
Link: https://www.amazon.com/dp/B0BQGGP2XT
AltLink: https://craphound.com/category/lostcause/
Annote: verified shortened link works

Id: little-01
Type: article
Media: link
Title: The Lure of Obedience
Author: Little, Mat
Date: 2012-07-13
DateSeen:  2023-03-23
Publisher: New Compass
Link: http://new-compass.net/articles/lure-obedience
AltLink: https://tinyurl.com/3mvwex8t https://web.archive.org/web/20230323174314/http://new-compass.net/articles/lure-obedience https://archive.vn/GrqpI
Annote: See notes. AltLink web.archive.org, Added DateSeen, shortened Publisher

Id: macy-01
Type: book
Media: Ebook
Title: Coming back to life : the updated guide to the work that reconnects
Author: Macy, Joanna
Authors: Brown, Molly Young
Date: 2014
Publisher: New Society Publishers
Tags: biblio, important
ISBN: 1550925806
ASIN: B00LDYEX4Q
Link: https://www.amazon.com/Coming-Back-Life-Updated-Reconnects-ebook/dp/B00LDYEX4Q/
Annote: Revised ed. edition. Added Authors, added Link, shortened Publisher

Id: nfnc-01
Type: site
Media: org
Title: Home :: Network For a New Culture
Tags: culture, link, biblio, link
Date: 2023-09-03
Link: http://www.nfnc.org/
AltLink: https://tinyurl.com/bddmbw7t https://web.archive.org/web/20230903130952/https://www.nfnc.org/
Annote: Found newest archived page.

Id: wikipedia-48
Type: article
Media: link
Title: Dunbar's number
Date: 2023-06-20
Link: https://en.wikipedia.org/wiki/Dunbar%27s_number
AltLink: https://tinyurl.com/2xkt99ms https://web.archive.org/web/20230620060350/https://en.wikipedia.org/wiki/Dunbar's_number https://archive.vn/b1ora
Annote: Added web.archive.org to AltLink
