#!/bin/bash
# Usage:
#    mk-biblio-org <biblio.txt >gen/biblio.org
# Also requires: biblio-note.org

# --------------------
# Build map array to biblio-note.html
echo 'BEGIN {' >/tmp/mk-biblio.awk
grep '\*\* Id: ' biblio-note.org | awk '
{
  print "  tNoteList[\"" $3 "\"] = \"<a href=\\\"biblio-note.html#id-" $3 "\\\">See: biblio-note#id-" $3 "</a>\""
}
' >>/tmp/mk-biblio.awk
echo '}' >>/tmp/mk-biblio.awk

# --------------------
# Main filter
cat <<\EOF >>/tmp/mk-biblio.awk
/^#/ { next }
NF == 0 { next }
$1 == "Id:" {
  if (tNote != "") {
    print "   + Annote: " tNote
  }
  tNote = ""
  if ($2 in tNoteList) {
    tNote = tNoteList[$2]
  }
  print "** " $0
  next
}
{
  print "   + " $0
}
EOF

# --------------------
# Main

cat <<\EOF
#+BEGIN_EXPORT html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
<title>Bibliography</title>
<link rel="stylesheet"
      href="bib.css" />
</head>
<body>
#+END_EXPORT
* Bibliography
EOF

'date' +'- %F'
awk -f /tmp/mk-biblio.awk biblio.txt
